csv:
  -
    outdir: '/metrics/csv'
    period: 100
    timeunit: 'MILLISECONDS'
    predicate:
      color: "white"
      useQualifiedName: true
      patterns:
        - "^org.apache.cassandra.metrics.ThreadPools.CompletedTasks.request.ReadStage"
        - "^org.apache.cassandra.metrics.ThreadPools.CompletedTasks.request.MutationStage"
        - "^org.apache.cassandra.metrics.ThreadPools.CompletedTasks.request.RequestResponseStage"
        - "^org.apache.cassandra.metrics.ThreadPools.CompletedTasks.transport.Native-Transport-Requests"
