csv:
  -
    outdir: '/metrics/csv'
    period: 1
    timeunit: 'SECONDS'
    predicate:
      color: "white"
      useQualifiedName: true
      patterns:
        - "^org.apache.cassandra.metrics.ThreadPools.ActiveTasks.request.ReadStage"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.request.ReadStage"
        - "^org.apache.cassandra.metrics.ThreadPools.CompletedTasks.request.ReadStage"
